---
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
params:
  data_frame: NA
  resistant_level: "resistant"
  control_level: "control"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(stringr)
library(lme4)
library(purrr)
library(tidyr)
library(ggplot2)
library(tidyselect)
library(DT)
library(kableExtra)
library(multcomp)
library(forcats)
```


```{r data}

# data_frame <- openxlsx::read.xlsx(
#   "C:/Users/eduardogarcia/Documents/garcia_galea/t_monserrat/data/230322 table example for r script.xlsx"
# ) |>
#   janitor::clean_names() |>
#   dplyr::select(pdx_id, sensitivity, group, percent_ki67)

data_frame <- params$data_frame


df_names <- names(data_frame)
data_model <- data_frame |>
  mutate(
    "{df_names[1]}" := factor(.data[[df_names[1]]]),
    "{df_names[2]}" := factor(data_frame[[df_names[2]]]) |>
      fct_relevel(params$resistant_level),
    "{df_names[3]}" := factor(data_frame[[df_names[3]]]) |>
      fct_relevel(params$control_level),
    "{df_names[4]}" := .data[[df_names[4]]] / 100,
    weight_100 = 100
  )
```

---
title: "`r str_c(df_names[4], " ~ ", df_names[2], " x ", df_names[3])`"
---

```{r model}

# Model with random intercepts only
form1 <- call(
  "formula",
  str_c(
    df_names[4], " ~ ", df_names[2], " * ", df_names[3],
    " + (1 | ", df_names[1], ")"
  )
)
model1 <- glmer(
  eval(form1), data = data_model, family = "binomial", weights = weight_100
)

# Model with random intercepts and slopes
form2 <- call(
  "formula",
  str_c(
    df_names[4], " ~ ", df_names[2], " * ", df_names[3],
    " + (1 + ", df_names[3], " | ", df_names[1], ")"
  )
)
model2 <- glmer(
  eval(form2), data = data_model, family = "binomial", weights = weight_100
)

comp_models <- anova(model1, model2)

# If both models are different, we choose the best. If not, we choose the less
# complex (random intercepts only)
if (comp_models$`Pr(>Chisq)`[2] <= 0.05) {
  # The best model is allways on the second row.
  model <- get(rownames(comp_models)[2])
} else {
  model <- model1
}

```

```{r multcomp}

# The data_frame passed to this file MUST have...:
# - The sensitivity factor in the second column and the resistant level must be
#   the first one.
# - The treatment factor in the third column and the control level must be the 
#   first one.
sensitive_level <- levels(data_model[[2]])[2]
treatment_level <- levels(data_model[[3]])[2]

ContRes_ContSen <- str_c(
  str_c("[", params$control_level, " & ", params$resistant_level, "]" ), " - ",
  str_c("[", params$control_level, " & ", sensitive_level, "]" )
)
ContRes_TrtRes <- str_c(
  str_c("[", params$control_level, " & ", params$resistant_level, "]" ), " - ",
  str_c("[", treatment_level, " & ", params$resistant_level, "]" )
)
ContSen_TrtSen <- str_c(
  str_c("[", params$control_level, " & ", sensitive_level, "]" ), " - ",
  str_c("[", treatment_level, " & ", sensitive_level, "]" )
)
interaction <- str_c(df_names[2], ":", df_names[3], " interaction")


K <- rbind(
  "ContRes - ContSen" = c(0, 1, 0, 0),
  "ContRes - TrtRes"  = c(0, 0, 1, 0),
  "ContSen - TrtSen"  = c(0, 0, 1, 1),
  "Interaction"       = c(0, 0, 0, 1)
)

row.names(K) <- c(ContRes_ContSen, ContRes_TrtRes, ContSen_TrtSen, interaction)


summary <- glht(model, K) |> summary()

result <- tibble(
 Hypothesis = str_c(names(summary$test$coefficients), " = 0"),
 Estimate = summary$test$coefficients,
 `Std. Error` = summary$test$sigma,
 `z value` = summary$test$tstat,
 `p-value` = summary$test$pvalues
)

```


## Data

### Original Data

```{r data-table}
data_frame |> 
  mutate(
    across(1:3, factor)
  ) |> 
  datatable(data_frame, filter = "top")

```

### Data Structure

```{r}
rnd_fct <- str_c(
    str_c("__", df_names[1], "__"), "with",
    unique(data_frame[[1]]) |> length(),
    "subjects", sep = " "
  )

  sen_fct <- str_c(
    str_c("__", df_names[2], "__"), "with levels",
    str_c(
      str_c("__", levels(data_model[[2]]), "__"),
      c(" (resistant level)", " (sensible level)"),
      collapse = " and "
    ),
    sep = " "
  )

  trt_fct <- str_c(
    str_c("__", df_names[3], "__"), "with levels",
    str_c(
      str_c("__", levels(data_model[[3]]), "__"),
      c(" (control level)", " (treatment level)"),
      collapse = " and "
    ),
    sep = " "
  )
  
  resp <- str_c(
     str_c("__", df_names[4], "__"), sep = " "
  )


```


- **PDX** random factor: `r rnd_fct`
- **Sensitivity** fixed factor: `r sen_fct`
- **Treatment** fixed factor: `r trt_fct`
- **Response** variable: `r resp`

```{r}

data_model |> 
  count(.data[[df_names[2]]], .data[[df_names[3]]]) |> 
  kbl() |> 
  kable_styling(full_width = FALSE)

```


## Graphic

```{r}

paired_data <- data_frame |> 
  group_by(.data[[df_names[1]]], .data[[df_names[2]]], .data[[df_names[3]]]) |> 
  summarise(
    "{df_names[4]}" := mean(.data[[df_names[4]]]),
    .groups = "drop"
  )

ggplot(paired_data, aes(.data[[df_names[3]]], .data[[df_names[4]]])) +
  facet_wrap(~ .data[[df_names[2]]]) +
  geom_point(cex = 2) +
  geom_line(aes(group = .data[[df_names[1]]])) +
  theme_classic() +
  theme(strip.background = element_blank(), text=element_text(size=20))


```


## Result

### Hypothesis Testing
```{r multcomp-tbl}

kbl(result) |> 
  kable_styling(full_width = FALSE)
 
```

### Model Summary
```{r model-summary}

summary(model)

```





