---
title: "PDX Response"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
params:
  data_frame: NA
  method: "profile"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(stringr)
library(lme4)
library(purrr)
library(tidyr)
library(ggplot2)
library(tidyselect)
library(DT)
library(kableExtra)
```

```{r data}

data_frame <- params$data_frame

df_names <- names(data_frame)
data_analysis <- data_frame |>
  mutate(
    "{df_names[4]}" := .data[[df_names[4]]] / 100,
    across(1:3, factor),
    weight_100 = 100
  )
```

```{r model}

# Model with random intercepts only
form1 <- call(
  "formula",
  str_c(
    df_names[4], " ~ ", df_names[2], " * ", df_names[3],
    " + (1 | ", df_names[1], ")"
  )
)
model1 <- glmer(
  eval(form1), data = data_analysis, family = "binomial", weights = weight_100
)

# Model with random intercepts and slopes
form2 <- call(
  "formula",
  str_c(
    df_names[4], " ~ ", df_names[2], " * ", df_names[3],
    " + (1 + ", df_names[3], " | ", df_names[1], ")"
  )
)
model2 <- glmer(
  eval(form2), data = data_analysis, family = "binomial", weights = weight_100
)

comp_models <- anova(model1, model2)

# If both models are different, we choose the best. If not, we choose the less
# complex (random intercepts only)
if (comp_models$`Pr(>Chisq)`[2] <= 0.05) {
  # The best model is allways on the second row.
  model <- get(rownames(comp_models)[2])
} else {
  model <- model1
}

```

```{r coefficients}
model_summary <- summary(model)

# Coefficients Confidence Intervals 
intervals <- confint(model, method = params$method, parm = "beta_")

coef_int <- list(
  # Lower coefficient values
  intervals[, 1],
  # Coefficients values
  model_summary$coefficients[, 1],
  # Upper coefficients values
  intervals[, 2]
)

```

```{r estimates}

sensitivity_levels <- levels(data_analysis[[2]])
treatment_levels <- levels(data_analysis[[3]])

parameters <- tibble(
  "{str_c(treatment_levels[1], '___', sensitivity_levels[1])}" := c(1, 0, 0, 0),
  "{str_c(treatment_levels[1], '___', sensitivity_levels[2])}" := c(1, 1, 0, 0),
  "{str_c(treatment_levels[2], '___', sensitivity_levels[1])}" := c(1, 0, 1, 0),
  "{str_c(treatment_levels[2], '___', sensitivity_levels[2])}" := c(1, 1, 1, 1),
)

estimates <- map_df(
  parameters,
  function(x) {
    map_dbl(coef_int, ~ sum(. * x) |> boot::inv.logit()) * 100
  }
) |>
  mutate(
    interval = c("lower", "value", "upper")
  ) |>
  pivot_longer(cols = 1:4) |>
  mutate(
    "{df_names[3]}" := str_remove(name, "___.+$"),
    "{df_names[2]}" := str_remove(name, "^.+___")
  ) |>
  select(
    all_of(c(df_names[2], df_names[3])), interval, value
  ) |>
  pivot_wider(names_from = interval, values_from = value)

```

```{r treatment-OR}
or_params <- tibble(
  "{str_c('OR_', sensitivity_levels[1])}" := c(0, 0, 1, 0),
  "{str_c('OR_', sensitivity_levels[2])}" := c(0, 0, 1, 1),
)

or_estimates <- map_df(
  or_params,
  function(x) {
    map_dbl(coef_int, ~ sum(. * x) |> exp())
  }
) |>
  mutate(
    interval = c("lower", "value", "upper")
  ) |> 
  pivot_longer(1:2) |> 
  pivot_wider(names_from = interval, values_from = value) |> 
  mutate(
    name = str_remove(name, "^OR_")
  ) |> 
  rename(
    "{df_names[2]}" := name
  )
```


Data
================================================================================


```{r data-table}
data_frame |> 
  mutate(
    across(1:3, factor)
  ) |> 
  DT::datatable(
    data_frame,
    filter = "top", options = list(paging = FALSE)
  )

```


Exploration
================================================================================

Column
--------------------------------------------------------------------------------
### **Raw Data**

```{r raw-plot, fig.width=8, fig.asp=1}

ggplot(data_frame, aes(.data[[df_names[3]]], .data[[df_names[4]]])) +
  facet_grid( ~ .data[[df_names[2]]]) +
  geom_boxplot() +
  geom_jitter()
```

Column
--------------------------------------------------------------------------------
### **Paired by PDX**

```{r paired-plot, fig.width=8, fig.asp=1}
paired_data <- data_frame |> 
  group_by(.data[[df_names[1]]], .data[[df_names[2]]], .data[[df_names[3]]]) |> 
  summarise(
    "{df_names[4]}" := mean(.data[[df_names[4]]])
  )


ggplot(paired_data, aes(.data[[df_names[3]]], .data[[df_names[4]]])) +
  facet_wrap(~ .data[[df_names[2]]]) +
  geom_point() +
  geom_line(aes(group = .data[[df_names[1]]]))

```


Analysis
================================================================================

Column {.tabset}
--------------------------------------------------------------------------------

### **Estimates**

**`r df_names[4]` estimates**
```{r estimates-tbl}
estimates |> 
  mutate(
    across(lower:upper, ~round(., 1))
  ) |> 
  kbl(format = "pipe")
```

**Odds `r treatment_levels[2]` / Odds `r treatment_levels[1]`**

```{r OR-tbl}
or_estimates |> 
  mutate(
    across(lower:upper, ~round(., 3))
  ) |> 
  kbl(format = "pipe")
```


### **Summary**
```{r summary}
model_summary
```


Column
--------------------------------------------------------------------------------

###

```{r estimates-plot, fig.width=12, fig.asp=0.62}

ggplot(
  estimates, aes(
    .data[[df_names[3]]], value,
    group = .data[[df_names[2]]], color = .data[[df_names[2]]]
  )
) +
  geom_line(
    aes(
      .data[[df_names[3]]], .data[[df_names[4]]], 
      group = .data[[df_names[1]]], color = .data[[df_names[2]]]
    ),
    paired_data, alpha = 1/3
  ) +
  geom_line(position = position_dodge(width = 0.1), linewidth = 1) +
  geom_point(position = position_dodge(width = 0.1)) +
  geom_pointrange(
    aes(ymin = lower, ymax = upper),
    position = position_dodge(width = 0.1), linewidth = 1
  ) +
  ylab(df_names[4]) +
  ylim(0, 100)

```

