#' @importFrom stats formula
NULL

#' Plot Dots, Boxplot, and Violin Plot
#'
#' This function generates a composite plot that includes a half violin plot, a half dot plot,
#' and a boxplot. It also adds statistical comparisons between groups.
#'
#' @param data A data frame containing the variables for plotting.
#' @param x A string representing the name of the x variable (categorical).
#' @param y A string representing the name of the y variable (numeric).
#' @param no_violin Logical indicating if the half violin plot should be removed.
#' @param compare Logical indicating if a statistical comparison should be added.
#' @param p_adj A string indicating the method to adjust the p-values. See \link[stats]{p.adjust}.
#' @param brackets_pos A numeric value indicating the relative position of the brackets that represent the statistical comparison.
#' @param ... Additional arguments to be passed to \link[ggpubr]{geom_bracket} (the function used to add the brackets).
#' @details The data used for the plot is stored as an attribute of the returned ggplot object called `data`
#' @return A ggplot object that can be further customized.
#' @export
ody_plot_violindotbox <- function(
    data, x, y,
    no_violin = FALSE,
    compare = FALSE,
    p_adj = "fdr",
    brackets_pos = 1.05,
    ...) {

  rlang::check_installed(c("ggpubr", "gghalves"))

  if (!is.factor(data[[x]])) {

    data[[x]] <- factor(data[[x]])

  }

  if (no_violin) {

    p <-
      ggplot2::ggplot(data, ggplot2::aes(.data[[x]], .data[[y]])) +
      ggplot2::geom_boxplot(outliers = FALSE) +
      ggplot2::geom_jitter(alpha = 0.5, width = 0.2)

  } else {

    p <-
      ggplot2::ggplot(data, ggplot2::aes(.data[[x]], .data[[y]])) +
      gghalves::geom_half_violin(side = "r") +
      ggplot2::geom_boxplot(width = 0.1, outliers = FALSE, fill = "gray") +
      gghalves::geom_half_point(side = "l", alpha = 0.5)

  }

  if (compare) {

    stats <-
      ggpubr::compare_means(
        formula(glue::glue("{y} ~ {x}")),
        data = data, p.adjust.method = p_adj
      )

    y_pos <- max(data |> dplyr::pull(.data[[y]]), na.rm = TRUE) * brackets_pos

    p <-
      p +
      ggpubr::geom_bracket(
        data = stats,
        ggplot2::aes(
          xmin = .data[["group1"]], xmax = .data[["group2"]],
          label = gtsummary::style_pvalue(.data[["p.adj"]])
        ),
        y.position = y_pos, ...
      )

  }

  data <- data |> dplyr::select(.data[[x]], .data[[y]])
  attr(p, "data") <- data
  p

}



#' Add descriptive table to a "Violindotbox" plot
#'
#' @param p A ggplot object generated by \code{ody_plot_violindotbox}.
#' @param n_dec Number of decimals to show in the descriptive table.
#'
#' @return A patchwork object that combines the original plot and the descriptive table.
#' @export
ody_add_tbl_violindotbox <- function(p, n_dec = 1, add_test = FALSE) {

  rlang::check_installed(c("patchwork"))

  data <- attr(p, "data")
  x <- names(data)[1]
  y <- names(data)[2]

  desc_tbl <-
    data |>
    dplyr::group_by(.data[[x]]) |>
    dplyr::summarise(
      N = sum(!is.na(.data[[y]])),
      min = min(.data[[y]], na.rm = TRUE),
      q1 = quantile(.data[[y]], 0.25, na.rm = TRUE),
      median = quantile(.data[[y]], 0.5, na.rm = TRUE),
      q3 = quantile(.data[[y]], 0.75, na.rm = TRUE),
      max = max(.data[[y]], na.rm = TRUE),
      mean = mean(.data[[y]], na.rm = TRUE),
      sd = sd(.data[[y]], na.rm = TRUE)
    ) |>
    dplyr::mutate(
      dplyr::across(min:sd, ~round(., n_dec)),
      N = as.character(N),
      `Mean (SD)` = stringr::str_c(mean, " (", sd, ")"),
      `Median (IQR)` = stringr::str_c(median, " (", q1, ", ", q3, ")"),
      `Min - Max` = stringr::str_c(min, ", ", max)
    ) |>
    dplyr::select(-min, -q1, -median, -q3, -max, -mean, -sd) |>
    tidyr::pivot_longer(
      cols = -tidyselect::all_of(x),
      names_to = "stat",
      values_to = "value"
    ) |>
    tidyr::pivot_wider(
      names_from = tidyselect::all_of(x),
      values_from = "value"
    ) |>
    gt::gt(rowname_col = "stat") |>
    gt::cols_align(align = "center") |>
    gt::cols_align(align = "right", columns = "stat")


  if (add_test) {

    ncases <- length(unique(data[[1]]))

    if ((ncases) == 2) {
      test <- "wilcox.test"
    } else {
      test <- "kruskal.test"
    }

    result <-
      ody_glue2lang(
        "{test}({names(data)[2]} ~ {names(data)[1]}, data = data)", .eval = TRUE
      )

    result_text <-
      stringr::str_c(
        names(result$statistic), " = ",
        round(result$statistic, 2), ", df = ", result$parameter,
        ", ", gtsummary::style_pvalue(result$p.value, prepend_p = TRUE)
      ) |>
      stringr::str_remove(" df = ,")

    desc_tbl <-
      desc_tbl |>
      gt::tab_footnote(result_text)

  }

  p <- p +
    ggplot2::labs(x = NULL) +
    ggplot2::theme(
      axis.text.x = ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank()
    )

  patchwork::wrap_plots(
    p, patchwork::wrap_table(desc_tbl, space = "fixed", ignore_tag = TRUE),
    ncol = 1
  )

}


