# Funcion para crear las filas de la tabla final a partir de las lineas extraidas
make_analite_row <- function(line_split_raw) {

  is_arrow <- stringr::str_detect(line_split_raw, "\\u2193|\\u2191")
  is_lower <- stringr::str_detect(line_split_raw, "^\\u2193$") |> any()
  is_very_lower <- stringr::str_detect(line_split_raw, "^\\u2193\\u2193$") |> any()
  is_upper <- stringr::str_detect(line_split_raw, "^\\u2191$") |> any()
  is_very_upper <- stringr::str_detect(line_split_raw, "^\\u2191\\u2191$") |> any()

  if (is_lower) {
    valor_rango <- "low"
  } else if (is_upper) {
    valor_rango <- "high"
  } else if (is_very_lower) {
    valor_rango <- "very low"
  } else if (is_very_upper) {
    valor_rango <- "very high"
  } else {
    valor_rango = "normal"
  }

  line_split <- line_split_raw[!is_arrow]

  tibble::tibble(
    analito = line_split[1],
    valor = line_split[2],
    unidad = line_split[3],
    rango = line_split[4],
    valor_rango = valor_rango
  )

}
# A veces la info del analito esta 1 o 2 filas mas abajo de la de su nombre,
# esta funcion va a esas filas para obtener la info faltante
correct_fail_data <- function(lab_tbl, line_pos, lab_split) {

  fail_cases <-
    lab_tbl |>
    dplyr::filter(is.na(.data[["valor"]])) |>
    dplyr::pull(.data[["line_index"]])

  lines_index_fail <- fail_cases + line_pos

  fail_data <- lab_split[lines_index_fail] |>
    stringr::str_replace_all(" {2,}", "::") |>
    stringr::str_replace("::-::", " - ") |>
    stringr::str_remove("::\\.$") |>
    stringr::str_split("::")

  values_fail <-
    fail_data |>
    purrr::map_chr(
      function(x) {
        if (is.null(x[2])) return(NA)
        x[2]
      }
    )

  units_fail <-
    fail_data |>
    purrr::map_chr(
      function(x) {
        if (is.null(x[3])) return(NA)
        x[3]
      }
    )

  range_fail <-
    fail_data |>
    purrr::map_chr(
      function(x) {
        if (is.null(x[4])) return(NA)
        x[4]
      }
    )

  lab_tbl[lab_tbl$line_index %in% fail_cases, "valor"] <- values_fail
  lab_tbl[lab_tbl$line_index %in% fail_cases, "unidad"] <- units_fail
  lab_tbl[lab_tbl$line_index %in% fail_cases, "rango"] <- range_fail

  lab_tbl

}



#' Extract Vall d'Hebron lab data from a PDF
#'
#' This function extracts the lab data from a PDF file generated by the Vall
#'  d'Hebron
#'
#' @param pdf_path Path to the PDF file.
#' @param write_xlsx Logical indicating if the extracted data should be written
#' to an xlsx file
#'
#' @return A tibble containing the extracted and processed lab data.
#'
#' @export
ody_extract_vhlab_pdf <- function(pdf_path, write_xlsx = TRUE) {

  rlang::check_installed("pdftools")
  if (write_xlsx) rlang::check_installed("openxlsx")

  lab_pdf <- pdftools::pdf_text(pdf_path)

  lab <- lab_pdf |> purrr::reduce(stringr::str_c)

  lab_split <- lab |> stringr::str_split("\\n", simplify = TRUE)

  # Patrones indicativos de que la linea contiene analito
  # versión con caracteres no ASCII
  # patrones <- c(
  #   "Hematies",
  #   "Hemoglobina",
  #   "Hematòcrit",
  #   "Volum corpuscular mig",
  #   "Concentració HGB Corpuscular mitja",
  #   "Ample Distribució Eritrocits",
  #   "^San-",
  #   "Reticulòcits",
  #   "Leucòcits",
  #   "Neutròfils",
  #   "Limfòcits",
  #   "Monòcits",
  #   "Eosinòfils",
  #   "Basòfils",
  #   "Plaquetes",
  #   "Volum plaquetari mig",
  #   "^Uri-",
  #   "Urocultiu",
  #   "^Pla-",
  #   "Antiglobulina directa",
  #   "^Srm-",
  #   "^Hb\\(San\\)",
  #   "^Pac-",
  #   "^vSan-",
  #   "^Hb\\(vSan\\)",
  #   "Calci iònic",
  #   "HIV-1/-2. Ac. totals i Ag p24",
  #   "Antigen superfície VHB",
  #   "Ac. anti-",
  #   "Hemocultiu",
  #   "Criofibrinògen"
  # )
  patrones <- c(
    "Hematies",
    "Hemoglobina",
    "Hemat\\u00f2crit",
    "Volum corpuscular mig",
    "Concentraci\\u00f3 HGB Corpuscular mitja",
    "Ample Distribuci\\u00f3 Eritrocits",
    "^San-",
    "Reticul\\u00f2cits",
    "Leuc\\u00f2cits",
    "Neutr\\u00f2fils",
    "Limf\\u00f2cits",
    "Mon\\u00f2cits",
    "Eosin\\u00f2fils",
    "Bas\\u00f2fils",
    "Plaquetes",
    "Volum plaquetari mig",
    "^Uri-",
    "Urocultiu",
    "^Pla-",
    "Antiglobulina directa",
    "^Srm-",
    "^Hb\\(San\\)",
    "^Pac-",
    "^vSan-",
    "^Hb\\(vSan\\)",
    "Calci i\\u00f2nic",
    "HIV-1/-2. Ac. totals i Ag p24",
    "Antigen superf\\u00edcie VHB",
    "Ac. anti-",
    "Hemocultiu",
    "Criofibrin\\u00f2gen"
  )

  # Lineas con analito
  lines_index <- stringr::str_detect(
    lab_split, stringr::str_c(patrones, collapse = "|")
  ) |> which()

  # Lineas con analito extraidas y limpiadas
  lines_split <-
    lab_split[lines_index] |>
    stringr::str_replace_all(" {2,}", "::") |>
    stringr::str_replace("::-::", " - ") |>
    stringr::str_remove("::\\.$") |>
    stringr::str_split("::")

  # extraccion de informacion de los analitos
  lab_tbl <-
    lines_split |>
    purrr::map_dfr(make_analite_row) |>
    dplyr::mutate(
      line_index = lines_index,
      valor = dplyr::case_when(
        .data[["valor"]] == "." ~ NA,
        .default = .data[["valor"]]
      )
    )

  nhc <- stringr::str_extract(lab, "NHC: +\\d+") |>
    stringr::str_extract("\\d+")

  recepcion <- stringr::str_extract(lab, "Data recepci\\u00f3: +\\d{2}/\\d{2}/\\d{2}") |>
    stringr::str_extract("\\d{2}/\\d{2}/\\d{2}") |>
    lubridate::dmy()

  if (is.na(recepcion)) {
    recepcion <- stringr::str_extract(lab, "Recepci\\u00f3: +\\d{2}/\\d{2}/\\d{2}") |>
      stringr::str_extract("\\d{2}/\\d{2}/\\d{2}") |>
      lubridate::dmy()
  }

  #
  # emision <- str_extract(lab, "Data emisi\\u00f3: +\\d{2}/\\d{2}/\\d{2}") |>
  #   str_extract("\\d{2}/\\d{2}/\\d{2}") |>
  #   dmy()
  #
  # cierre <- str_extract(lab, "Data tancament: +\\d{2}/\\d{2}/\\d{2}") |>
  #   str_extract("\\d{2}/\\d{2}/\\d{2}") |>
  #   dmy()
  #
  # nacimiento <- str_extract(lab, "Nascut el: +\\d{2}/\\d{2}/\\d{4}") |>
  #   str_extract("\\d{2}/\\d{2}/\\d{4}") |>
  #   dmy()

  final_tbl <-
    lab_tbl |>
    correct_fail_data(1, lab_split) |>
    correct_fail_data(2, lab_split) |>
    dplyr::select(-"line_index") |>
    dplyr::mutate(
      #A veces no hau unidad y el rango se cuela en la casilla de la unidad
      rango_en_unidades = is.na(.data[["rango"]]) & stringr::str_detect(.data[["unidad"]], " - "),
      rango = dplyr::if_else(
        .data[["rango_en_unidades"]], .data[["unidad"]], .data[["rango"]]
      ),
      unidad = dplyr::if_else(
        .data[["rango_en_unidades"]], NA, .data[["unidad"]]
      ),
      valor_rango = dplyr::if_else(
        is.na(.data[["rango"]]), NA, .data[["valor_rango"]]
      )
    ) |>
    dplyr::select(-"rango_en_unidades") |>
    dplyr::mutate(
      nhc = nhc,
      # nacimiento = nacimiento,
      recepcion = recepcion,
      # emision = emision,
      # cierre = cierre,
      .before = 1
    )

  if (write_xlsx) {
    xlsx_path <- stringr::str_replace(pdf_path, "\\.pdf$|\\.PDF$", ".xlsx")
    openxlsx::write.xlsx(final_tbl, xlsx_path)
  }

  final_tbl

}


